[package]
name = "raytracer"
version = "0.1.0"
authors = ["eperdew <eperdew17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "*"
float-ord = "*"
image = "*"
itertools = "*"